# Generated by Django 4.2.5 on 2023-09-15 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stud1',
            new_name='stud',
        ),
    ]
